version: '3.3'
services:

  api:
    build: app/
    container_name: mygoapp
    ports:
      - "8080:8080"
    volumes:
      - "/home/msurfer/project_root/app/src:/app"
    command: bash -c "cd /app/cmd/ && go get -d -v && go build -o main && ./main"
    restart: unless-stopped
    depends_on:
    - db
    - web-server


  db:
    build: redis/
    container_name: redisdb
    ports:
      - "6379:6379"
    restart: unless-stopped


  web-server:
    build: nginx/
    container_name: mynginxproxy
    ports:
      - "8089:80"
    volumes:
      - "/home/msurfer/project_root/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    restart: unless-stopped