version: '3.3'
services:

  api:
    build: app/
    container_name: mygoapp
    network_mode: "host"
    restart: unless-stopped
    depends_on:
    - db
    - web-server


  db:
    build: redis/
    container_name: redisdb
    network_mode: "host"
    restart: unless-stopped


  web-server:
    build: nginx/
    container_name: mynginxproxy
    network_mode: "host"
    restart: unless-stopped